version: "3"
services:
  mysql:
    image: mariadb
    container_name: snipe_mysql
    restart: always
    volumes:
      - MariaDB-DATA:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD=MEU8dv99q
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=MEU8dv99q
      - MYSQL_DATABASE=snipe
  snipeit:
    image: snipe/snipe-it
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - SnipeIT_DT:/config
    environment:
      - NGINX_APP_URL=192.168.1.3:8080
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=<secret user password>
      - PGID=1000
      - PUID=1000
    ports:
      - "8080:80"
    Volumes:
      - MariaDB-DATA
      - SnipeIT_DT